name: medisync
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.0
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  fluttertoast: ^8.2.2
  flutter_timezone: ^1.0.7
  sqflite: ^2.3.0
  path: ^1.8.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

# flutter launcher icon settings
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_mini.png"

# flutter_native_splash settings
flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"
  fullscreen: true
